# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static\\img\\201903/08')),
                ('username', models.CharField(max_length=25)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wechatupdate',
                'ordering': ['-create_time'],
            },
        ),
    ]
